function Reports() {
  // Temporary data
  const totalSales = 0;
  const totalExpenses = 0;
  const totalProducts = 0;

  const estimatedProfit = totalSales - totalExpenses;

  return (
    <div>
      {/* Page Heading */}
      <div>
        <p className="font-semibold tracking-widest text-[var(--status)]">
          BUSINESS REPORTS
        </p>

        <h1 className="mt-2 text-3xl font-bold md:text-4xl">
          Understand your business performance.
        </h1>

        <p className="mt-3 text-[var(--muted-text)]">
          View important business information and financial summaries.
        </p>
      </div>

      {/* Report Summary */}
      <section className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">

        {/* Total Sales */}
        <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6">
          <p className="text-sm text-[var(--muted-text)]">
            Total Sales
          </p>

          <h2 className="mt-3 text-3xl font-bold">
            ₦{totalSales.toLocaleString()}
          </h2>

          <p className="mt-2 text-sm text-[var(--muted-text)]">
            Total recorded sales
          </p>
        </div>

        {/* Total Expenses */}
        <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6">
          <p className="text-sm text-[var(--muted-text)]">
            Total Expenses
          </p>

          <h2 className="mt-3 text-3xl font-bold">
            ₦{totalExpenses.toLocaleString()}
          </h2>

          <p className="mt-2 text-sm text-[var(--muted-text)]">
            Total recorded expenses
          </p>
        </div>

        {/* Estimated Profit */}
        <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6">
          <p className="text-sm text-[var(--muted-text)]">
            Estimated Profit
          </p>

          <h2 className="mt-3 text-3xl font-bold">
            ₦{estimatedProfit.toLocaleString()}
          </h2>

          <p className="mt-2 text-sm text-[var(--muted-text)]">
            Sales minus expenses
          </p>
        </div>

        {/* Products */}
        <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6">
          <p className="text-sm text-[var(--muted-text)]">
            Total Products
          </p>

          <h2 className="mt-3 text-3xl font-bold">
            {totalProducts}
          </h2>

          <p className="mt-2 text-sm text-[var(--muted-text)]">
            Products in inventory
          </p>
        </div>

      </section>

      {/* Performance Summary */}
      <section className="mt-10 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6">
        <h2 className="text-xl font-bold">
          Performance Summary
        </h2>

        <div className="mt-6">
          {totalSales === 0 && totalExpenses === 0 ? (
            <div className="py-10 text-center">
              <p className="text-lg font-semibold">
                No business data available yet.
              </p>

              <p className="mt-2 text-[var(--muted-text)]">
                Start recording sales and expenses to generate
                business reports.
              </p>
            </div>
          ) : (
            <div>
              <p className="text-[var(--muted-text)]">
                Your business has generated ₦
                {totalSales.toLocaleString()} in sales and recorded ₦
                {totalExpenses.toLocaleString()} in expenses.
              </p>

              <div className="mt-6">
                <p className="font-medium">
                  Estimated Profit
                </p>

                <p className="mt-2 text-3xl font-bold">
                  ₦{estimatedProfit.toLocaleString()}
                </p>
              </div>
            </div>
          )}
        </div>
      </section>

      {/* Report Information */}
      <section className="mt-10 grid gap-5 lg:grid-cols-2">

        <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6">
          <h2 className="text-xl font-bold">
            Sales Report
          </h2>

          <p className="mt-3 text-[var(--muted-text)]">
            Review your sales performance and monitor revenue
            generated by your business.
          </p>

          <p className="mt-5 font-semibold text-[var(--primary)]">
            ₦{totalSales.toLocaleString()}
          </p>
        </div>

        <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6">
          <h2 className="text-xl font-bold">
            Expense Report
          </h2>

          <p className="mt-3 text-[var(--muted-text)]">
            Monitor your business spending and understand where
            your money is being used.
          </p>

          <p className="mt-5 font-semibold text-[var(--primary)]">
            ₦{totalExpenses.toLocaleString()}
          </p>
        </div>

      </section>
    </div>
  );
}

export default Reports;